services:
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hinario
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  hinario-app:
    build: .
    container_name: hinario-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/hinario
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
volumes:
  postgres_data:
